// services/ragService.js
// Core RAG pipeline: index a document into Pinecone, query it for relevant chunks.
//
// FLOW:
//   indexDocument(docId, text)
//     → chunk text
//     → embed each chunk via OpenAI
//     → upsert vectors into Pinecone (namespaced by docId)
//
//   retrieveRelevantChunks(docId, question, topK)
//     → embed the question
//     → query Pinecone for topK nearest vectors in this doc's namespace
//     → return the matching text chunks

const { Pinecone } = require("@pinecone-database/pinecone");
const OpenAI = require("openai/index.mjs");
const chunkText = require("../utils/chunkText");
const { PINECONE_API_KEY, PINECONE_INDEX_NAME, OPENAI_API_KEY } = require("../config/env");

const pinecone = new Pinecone({ apiKey: PINECONE_API_KEY });
const openai = new OpenAI({ apiKey: OPENAI_API_KEY });

// Get the Pinecone index — done once, reused across requests
const getIndex = () => pinecone.index(PINECONE_INDEX_NAME);

// Generate an embedding vector for a piece of text using OpenAI's embedding model.
// An embedding is a fixed-length array of floats (1536 numbers for text-embedding-3-small)
// that represents the semantic meaning of the text. Similar meanings → similar vectors.
const embedText = async (text) => {
  const response = await openai.embeddings.create({
    model: "text-embedding-3-small", // cheapest + fastest OpenAI embedding model, good quality
    input: text,
  });
  return response.data[0].embedding; // returns the float array
};

// Index (or re-index) an entire document into Pinecone.
// Called when: a document is first created, or after significant edits.
// In practice, the frontend triggers this via POST /api/ai/index after auto-save.
const indexDocument = async (documentId, plainText) => {
  const index = getIndex();
  const chunks = chunkText(plainText, 500, 100);

  // Build vectors array for batch upsert
  const vectors = await Promise.all(
    chunks.map(async (chunk, i) => {
      const embedding = await embedText(chunk);
      return {
        id: `${documentId}_chunk_${i}`, // unique ID per chunk
        values: embedding,              // the actual vector
        metadata: {
          documentId,
          chunkIndex: i,
          text: chunk, // store the original text in metadata so we can return it on retrieval
        },
      };
    })
  );

  // Upsert into Pinecone — "upsert" = insert if new, update if ID already exists
  // We namespace by documentId so queries are scoped to one document only
  await index.namespace(documentId).upsert(vectors);

  return { chunksIndexed: vectors.length };
};

// Retrieve the most relevant text chunks for a given question, scoped to one document.
const retrieveRelevantChunks = async (documentId, question, topK = 5) => {
  const index = getIndex();

  // Embed the question using the same model as the chunks
  // WHY same model: embeddings are only comparable if generated by the same model
  const questionEmbedding = await embedText(question);

  // Query Pinecone: find topK vectors closest to the question vector
  const results = await index.namespace(documentId).query({
    vector: questionEmbedding,
    topK,
    includeMetadata: true, // we need the stored text chunks back
  });

  // Extract the text from matching chunks, ordered by relevance (Pinecone returns by score desc)
  return results.matches.map((match) => match.metadata.text);
};

// Delete all vectors for a document (called when document is deleted)
const deleteDocumentIndex = async (documentId) => {
  const index = getIndex();
  await index.namespace(documentId).deleteAll();
};

module.exports = { indexDocument, retrieveRelevantChunks, deleteDocumentIndex };
